### ISSUE TITLE
Getting the plugin working

### ISSUE THREAD

**Issue by NetAppBlueDevil** [inventage/nexus-apt-plugin#10]
I'm trying to get the plug working with Nexus 2.10.0-02 OSS version.  My Nexus is running on a RHEL 6.5 system.

I have installed the plugin 1.0.1 version and see it listed as activated.
I have a hosted repository for testing and I see a Packages.gz on the repo URL
I have uploaded a module which contains a single .deb file.
I do not see the Package.gz being updated with any information about this uploaded package

Looking into the log file, I see this stack trace which looks to include classes from this plugin.  It appears to be something about a Keyring location, but I don't know what this is based on the Readme.  Is there something else that needs to be configured.

jvm 1    | 2015-01-14 10:36:24,633-0500 ERROR [qtp131312334-57] admin com.inventage.nexusaptplugin.MacPluginEventInspector - e
jvm 1    | org.sonatype.nexus.proxy.LocalStorageException: Got exception during storing on path "InternalHosted:/Release.gpg" (while writing to hiddenTarget: "/mnt/sonatype-work/nexus/storage/InternalHosted/.nexus/tmp/Release.gpgnx-tmp3185584856221267345.nx-upload")
jvm 1    | 	at org.sonatype.nexus.proxy.storage.local.fs.DefaultFSPeer.storeItem(DefaultFSPeer.java:144) ~[nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.storage.local.fs.DefaultFSLocalRepositoryStorage.storeItem(DefaultFSLocalRepositoryStorage.java:338) ~[nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.repository.AbstractRepository.storeItem(AbstractRepository.java:1007) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.maven.AbstractMavenRepository.storeItem(AbstractMavenRepository.java:463) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.inventage.nexusaptplugin.MacPluginEventInspector.updateOrInstallStorageItem(MacPluginEventInspector.java:178) [nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.MacPluginEventInspector.updateFileModificationDate(MacPluginEventInspector.java:155) [nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.MacPluginEventInspector.updateDebItemInRepository(MacPluginEventInspector.java:104) [nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.MacPluginEventInspector.onRepositoryItemEventStore(MacPluginEventInspector.java:94) [nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[na:na]
jvm 1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
jvm 1    | 	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.guava.EventHandler.handleEvent(EventHandler.java:80) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.guava.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:49) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.guava.EventBus.dispatch(EventBus.java:329) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.DefaultGuavaEventBus.dispatch(DefaultGuavaEventBus.java:34) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.ReentrantGuavaEventBus.dispatchQueuedEvents(ReentrantGuavaEventBus.java:57) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.guava.EventBus.post(EventBus.java:281) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.sisu.goodies.eventbus.internal.DefaultEventBus.post(DefaultEventBus.java:78) [goodies-eventbus-1.9.jar:1.9]
jvm 1    | 	at org.sonatype.nexus.proxy.repository.AbstractRepository.storeItem(AbstractRepository.java:1021) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.maven.AbstractMavenRepository.storeItem(AbstractMavenRepository.java:463) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.repository.AbstractRepository.storeItem(AbstractRepository.java:659) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.maven.ArtifactStoreHelper.storeItemWithChecksums(ArtifactStoreHelper.java:70) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.maven.AbstractMavenRepository.storeItemWithChecksums(AbstractMavenRepository.java:325) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.maven.ArtifactStoreHelper.storeArtifactWithGeneratedPom(ArtifactStoreHelper.java:411) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.rest.artifact.AbstractArtifactPlexusResource.upload(AbstractArtifactPlexusResource.java:391) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.sonatype.plexus.rest.resource.RestletResource.upload(RestletResource.java:350) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.sonatype.plexus.rest.resource.RestletResource.acceptRepresentation(RestletResource.java:250) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.sonatype.nexus.rest.NexusRestletResource.acceptRepresentation(NexusRestletResource.java:70) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.resource.Resource.post(Resource.java:688) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.resource.Resource.handlePost(Resource.java:537) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Finder.handle(Finder.java:357) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Router.handle(Router.java:504) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.sonatype.plexus.rest.RetargetableRestlet.doHandle(RetargetableRestlet.java:36) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.StatusFilter.doHandle(StatusFilter.java:130) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.ChainHelper.handle(ChainHelper.java:124) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.application.ApplicationHelper.handle(ApplicationHelper.java:112) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Application.handle(Application.java:341) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Router.handle(Router.java:504) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.doHandle(Filter.java:150) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Filter.handle(Filter.java:195) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Router.handle(Router.java:504) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.ChainHelper.handle(ChainHelper.java:124) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Component.handle(Component.java:676) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.restlet.Server.handle(Server.java:331) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.ServerHelper.handle(ServerHelper.java:68) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.http.HttpServerHelper.handle(HttpServerHelper.java:147) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at com.noelios.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:881) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at org.sonatype.nexus.restlet1x.internal.RestletServlet.service(RestletServlet.java:90) [nexus-restlet1x-plugin-2.10.0-02/:na]
jvm 1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
jvm 1    | 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:288) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:278) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:93) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.NexusGuiceFilter$MultiFilterChain.doFilter(NexusGuiceFilter.java:82) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.NexusGuiceFilter$MultiFilterChain.doFilter(NexusGuiceFilter.java:82) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.sonatype.nexus.analytics.internal.RestRequestCollector.doFilter(RestRequestCollector.java:82) [nexus-analytics-plugin-2.10.0-02/:na]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.sonatype.nexus.web.internal.SecurityFilter.executeChain(SecurityFilter.java:73) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.NexusGuiceFilter$MultiFilterChain.doFilter(NexusGuiceFilter.java:82) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.yammer.metrics.web.WebappMetricsFilter.doFilter(WebappMetricsFilter.java:76) [metrics-web-2.2.0.jar:na]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.CommonHeadersFilter.doFilter(CommonHeadersFilter.java:69) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.ErrorPageFilter.doFilter(ErrorPageFilter.java:71) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.BaseUrlHolderFilter.doFilter(BaseUrlHolderFilter.java:70) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.sonatype.nexus.web.internal.NexusGuiceFilter$MultiFilterChain.doFilter(NexusGuiceFilter.java:82) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.web.internal.NexusGuiceFilter$MultiFilterPipeline.dispatch(NexusGuiceFilter.java:56) [nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:132) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:129) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:206) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:129) [guice-servlet-3.1.10.jar:3.1.10]
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-security-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at com.yammer.metrics.jetty.InstrumentedHandler.handle(InstrumentedHandler.java:200) [metrics-jetty-2.2.0.jar:na]
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
jvm 1    | 	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
jvm 1    | Caused by: java.io.IOException: Could not generate Release.gpg
jvm 1    | 	at com.inventage.nexusaptplugin.FileManagerContentLocator.getContent(FileManagerContentLocator.java:40) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at org.sonatype.nexus.proxy.item.ChecksummingContentLocator.getContent(ChecksummingContentLocator.java:55) ~[nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.item.ChecksummingContentLocator.getContent(ChecksummingContentLocator.java:55) ~[nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	at org.sonatype.nexus.proxy.storage.local.fs.DefaultFSPeer.storeItem(DefaultFSPeer.java:118) ~[nexus-core-2.10.0-02.jar:2.10.0-02]
jvm 1    | 	... 145 common frames omitted
jvm 1    | Caused by: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Keyring location is not set and it could not be found automatically
jvm 1    | 	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2346) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.inventage.nexusaptplugin.cache.DebianFileManager.getFile(DebianFileManager.java:62) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.FileManagerContentLocator.getContent(FileManagerContentLocator.java:37) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	... 148 common frames omitted
jvm 1    | Caused by: java.io.FileNotFoundException: Keyring location is not set and it could not be found automatically
jvm 1    | 	at com.inventage.nexusaptplugin.sign.AptSigningConfiguration.getSigner(AptSigningConfiguration.java:68) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.cache.generators.ReleaseGPGGenerator.generateFile(ReleaseGPGGenerator.java:46) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.cache.DebianFileManager$1.call(DebianFileManager.java:66) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.inventage.nexusaptplugin.cache.DebianFileManager$1.call(DebianFileManager.java:62) ~[nexus-apt-plugin-1.0.1/:na]
jvm 1    | 	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[guava-16.0.1.jar:na]
jvm 1    | 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[guava-16.0.1.jar:na]
jvm 1    | 	... 154 common frames omitted

**Comment by Tangresh** [comment]
Can you please do a 'Update Index' on the Repository in question?
The empty Packages.gz  might be related to #8.

The stacktrace is generated if no gpg key is specified for the plugin. You can do that in Nexus by going to Administration -> Capabilities -> New -> Select 'APT: Configuration'. This is needed if you want your APT repository to be signed, but APT works just fine without it.

**Comment by NetAppBlueDevil** [comment]
So, I ran the gpg utility as the user that I run Nexus as and it created the .gnupg folder and files in my user directory that the class appeared to be looking for.  I had never done anything with this utility and I'm not sure that I have it complete.  How are the entries in the APT Configuration screen supposed to match with this gpg setup?  Is there something I need to do to create a keyring that matches to the passphrase I configure?

There was a slight change to my Packages file after rebuilding the index and metadata.  It now was no longer 0 bytes, but it still didn't contain information about my module.

**Comment by Tangresh** [comment]
The passphrase in the screen is supposed to match to the key you generated. During `gpg --gen-key` you are prompted for it.
The plugin tries to look for the secring.gpg file in a few default locations, such as the ~/.gnupg/secring.gpg, so you are not strictly required to provide a location. What you do need to provide is the ID of the signing key, which you can get with `gpg --list-keys`.
You should get something like this:
> pub   2048R/0BE12138 2015-01-14 [expires: 2017-01-13]
> uid                  Dominik Menzi (Tangresh) <dmenzi@tangresh.ch>
> sub   2048R/D0D50873 2015-01-14 [expires: 2017-01-13]
In this case the key ID is 0BE12138, the part after the slash.
Whether you have GPG enabled/configured or not should actually not influence the generation of the Packages/Packages.gz files, it just generates an ugly stacktrace, hence #1.

As for the Packages file, what are its new contents? Some other packages you uploaded or something completely unrelated?

**Comment by NetAppBlueDevil** [comment]
Cool, I think I have a key generated and configured correctly.  But from your last response that is probably not the issue.

The Packages file in the root of the repository only contains the text "PackagesContentGenerator" now

**Comment by NetAppBlueDevil** [comment]
Actually just detected that the version in my deb control file was not correct and didn't match the version in the maven repo structure.  Rebuilding to see what happens when I uploaded a corrected version.

**Comment by NetAppBlueDevil** [comment]
That looks to have been the problem.  I see the entries in the Package file once I got the version matching correctly.

Having seen the stack trace issue, I thought that was the cause of something not properly building that file.  Thanks for the help though in getting the gpg stuff set up correctly.

Now on to getting the apt-get half working

**Comment by Tangresh** [comment]
Did you look at the file on the disk? Because those files have only an identifier ("PackagesContentGenerator") as content. The actual Packages/Packages.gz files are generated on the fly when they are accessed through Nexus.

**Comment by NetAppBlueDevil** [comment]
Yes, I looked on disk to see the PackagesContentGenerator text.  Was still empty via the HTTP download.  I posted last update regarding having solved the problem in realizing the Version in my deb control file was not correct and matching the version that I had uploaded the deb to.  That correction got things working.

**Comment by Tangresh** [comment]
Ok, I'm glad you got it working. But for clarification, it should not be necessary to have the same version in the control file as you are uploading it to. We certainly don't do it that way.

**Comment by NetAppBlueDevil** [comment]
Sure.  In my case, I had it configured as a property replacement but had the wrong property name.  So the version value of ${theversion} probably had issues with the funky characters would be my guess.

**Comment by Tangresh** [comment]
Ok, thanks for clearing that up.
