### ISSUE TITLE
README information for sources.list

### ISSUE THREAD

**Issue by NetAppBlueDevil** [inventage/nexus-apt-plugin#11]
The README says to add this to /etc/apt/sources.list
deb http://repository.yourcompany.com/content/repositories/releases/Packages.gz ./

but that gave me an error when i did the apt-get update

Changing it to this
deb http://repository.yourcompany.com/content/repositories/releases/ ./
worked.

**Comment by Tangresh** [comment]
You are right, that is an error. I will correct this asap.
