### ISSUE TITLE
Re-Generate Index / Packages File

### ISSUE THREAD

**Issue by derjohn** [inventage/nexus-apt-plugin#13]
Hello,
how do I re-create the Packages* files? I upgraded to 1.0.2 in order do get the Provides: line, but in old package data it's still missing. I tried update and repair index, but Provides: does not show up. When upoading new packages, the Provides: is there.

rgds,
j

**Comment by derjohn** [comment]
Update: I initiated a 'manual run' on virtually evtherything that has to do with the index of that repo (repair, update, publish....) and even deleted the Packages file... The packages it now filled completely, bit I have no idea what are the right jobs to do it correctly.

**Comment by Tangresh** [comment]
I'm glad you could get it to work. I thought that repair+update regenerates the files, but I could be mistaken.

What should work though is what is in the README: delete the index files under sonatype-work/nexus/indexer and restart nexus.
