### ISSUE TITLE
apt index not updated consistently with new package versions

### ISSUE THREAD

**Issue by bedge** [inventage/nexus-apt-plugin#15]
Several times now I've had problems getting the nexus apt plugin to "recognize" that a new version of a package has been uploaded.
What I end having to do is bump the version again and re-upload so that it "sees" the next older one.

After uploading:
```
Deploying the main artifact nim-asset-manager-1.0.0-develop-94-all.deb
Uploading: http://nexus.nim.com:8081/nexus/content/repositories/releases/com/nim/ct/nim-asset-manager/1.0.0-develop-94/nim-asset-manager-1.0.0-develop-94-all.deb
Uploaded: http://nexus.nim.com:8081/nexus/content/repositories/releases/com/nim/ct/nim-asset-manager/1.0.0-develop-94/nim-asset-manager-1.0.0-develop-94-all.deb (11564 KB at 17055.8 KB/sec)
[INFO] Deployment in http://nexus.nim.com:8081/nexus/content/repositories/releases/ (id=nexus-releases,uniqueVersion=true)
```

I get the LATEST using:
```
curl -L 'http://nexus.nim.com:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.nim.ct&c=all&a=nim-asset-manager&v=LATEST&p=deb' -o xx.deb
```
and check the version, and it's not the latest.
```
%> dpkg -I xx.deb
 new debian package, version 2.0.
....
 Package: nim-asset-manager
 Version: 1.0.0+develop+55
```

Browsing the nexus UI shows that the new version is there:
![screen shot 2015-08-21 at 9 20 45 pm](https://cloud.githubusercontent.com/assets/499317/9422551/acb996aa-484c-11e5-99a0-51a5d2e84072.png)

Here's the relevant section of a nexus.log, grepped for 
e packages -e "nim-asset-manager-1.0.0-develop" -e apt -e deb
https://gist.github.com/01374b80e195a115d00a

**Comment by bedge** [comment]
After deleting the older version from the maven UI, the latest is being returned now.

**Comment by Tangresh** [comment]
I don't think this is related to the apt-plugin at all. All the plugin does is create a few virtual files so apt can use the repository (Packages, Packages.gz, ...).

The LATEST feature looks like a Nexus feature to me and is unrelated to the plugin.

**Comment by bedge** [comment]
Confirmed. Packages & Packages.gz are updated correctly. Unrelated to apt plugin.
