### ISSUE TITLE
Plugin download?

### ISSUE THREAD

**Issue by tykeal** [inventage/nexus-apt-plugin#17]
The README.md states that there is a downloads section to download the current builds. Where might this section be since it's not in the README?

**Comment by Tangresh** [comment]
Go to the 'Code' tab (on the right with the normal layout, top with the new layout), then Releases. You should find a list of the recent releases there, with source code archives as well as bundled builds.

**Comment by tykeal** [comment]
Thanks! I don't think I've ever noticed that before.
