### ISSUE TITLE
"corrupted filesystem tarfile - corrupted package archive" for arm packages

### ISSUE THREAD

**Issue by IainColledge** [inventage/nexus-apt-plugin#19]
I'm using Nexus with the apt plugin (excellent I may add) to host debian packages for two architectures, amd64 and armv7l. Nexus and apt work well expect there seems to be something that happens with the armv7l packages that results in corrupt packages when they get signed.

The package in question is td-agent and am building using team city build agents both running under docker with Ubuntu and Rasbian as the OS. The deb files produced are able to be installed on their native OS environments fine (dpkg -i) however when uploaded to Nexus (using the REST API) only the td-agent package is able to install, the arml7 package now throws up the error above using either apt or dpkg (after wget to download).

Both Raspbian and x86 are little endian so it wont be byte order.

Any thoughts?

**Comment by Tangresh** [comment]
No thoughts really, but maybe we can pinpoint the place where the corruption happens.

Can you try and upload a package to Nexus and then instead of downloading via apt/http copy the file from the filesystem in Nexus directly? If this file is already corrupt, then the corruption happens during the upload.

**Comment by IainColledge** [comment]
These are the files from their sources.

tc-artifact: 45463454 Feb 29 11:00 td-agent_2.3.1-0_armv7l.deb
nexus-fs: 45463454 Mar  2 12:55 td-agent-armv7l-2.3.1.deb
nexus-http: 47743470 Feb 25 12:27 td-agent-amd64-2.3.1.deb

**Comment by Tangresh** [comment]
Have you also tried this without the nexus-apt-plugin?

**Comment by Tangresh** [comment]
Can you compare some hash like md5 of tc-artifact and nexus-fs?
Also, the nexus-http file is amd64 and built earlier than the armv7l version, that seems to be the wrong file.

**Comment by IainColledge** [comment]
Opps my bad the http file size is 45463454

Having tried the nexus fs it seems that both come back with an error so must be the upload at fault which I'm basically doing with curl.

When I look at an md5sum of the files I get:

eadf09230ca800032370bcce2f9b47b7  td-agent_2.3.1-0_armv7l.deb.tc-artifact
863637506cb86ccaff75dc63ffe34245  td-agent-armv7l-2.3.1.deb
863637506cb86ccaff75dc63ffe34245  td-agent-armv7l-2.3.1.deb.nexus-fs

For the versions so the curl I'm using must be at fault, basically a script that goes

`REPO_URL=http://nexus.service.services.letsthinkonittonight.co.uk:8081
REPO_ID=homelab
GROUP_ID=logs
ARTIFACT_ID=td-agent-armv7l
PROJECT=monitoring
FILENAME=$(ls td-agent_*.deb)
VERSION=$(echo $FILENAME | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
PACKAGING=deb

curl -v \
    -F "r=$REPO_ID" \
    -F "hasPom=false" \
    -F "g=$GROUP_ID" \
    -F "a=$ARTIFACT_ID" \
    -F "v=$VERSION" \
    -F "p=$PACKAGING" \
    -F "file=@$FILENAME" \
    -u deployment:********* \
    $REPO_URL/service/local/artifact/maven/content`

Inspired from https://support.sonatype.com/hc/en-us/articles/213465818-How-can-I-programatically-upload-an-artifact-into-Nexus-

Looking around it probably needs --data-binary, so I'll run another build and put this in for the upload, will post back and thanks for the md5sum tip.

**Comment by IainColledge** [comment]
Tangresh after some experimentation this has nothing to do with your plugin and Nexus, and will be tracking it down, thanks very much for your help.
