### ISSUE TITLE
3.0 Support

### ISSUE THREAD

**Issue by BarnumD** [inventage/nexus-apt-plugin#24]
Please update the README with Nexus 3.x support.

**Comment by Tangresh** [comment]
There is no 3.x support. Nexus 3 has a completely different repository format and the plugin would have to be rewritten for 3.x. At the moment we don't have the time to do this.

**Comment by mshahat** [comment]
this was one of the few resources i found online on how to install nexus through apt-get ... is there any reason why sonatype is not providing such an installation channel ? 

any idea how can i get nexus 3.x installed through apt-get ? i am standardizing this to ease out upgrade ...etc. 

thanks in advance, 

Cheers, /Mo

**Comment by hagzag** [comment]
@mshahat I am not sure there is a dep package available ... and IMHO this issue is for hosting apt repos on nexus not how to install it.
@Tangresh is there any intention of migrating || rewriting the plugin for Nexus 3.0 ? - have you heard of someone else thinking of doing this ?

**Comment by b8** [comment]
Sonatype has the DEB format for nexus3 in future consideration, see also https://issues.sonatype.org/browse/NEXUS-3199. But it doesn't have a high priority so it would be great if someone would donate such a plug-in...

**Comment by mshahat** [comment]
well ... all i wanted is a .deb package to install Nexus3 , rather than Nexus3 supporting .deb packages. 

thanks all for answers so far,

**Comment by Tangresh** [comment]
Have a look at http://exchange.sonatype.com/details?extension=4719699238. Somebody else wrote a plugin for Nexus 3
