### ISSUE TITLE
Compatability with Sonatype Nexus OSS 3.2.0-01

### ISSUE THREAD

**Issue by rackovan** [inventage/nexus-apt-plugin#29]
Is this plugin compatible with Sonatype Nexus OSS 3.2.0-01?  I placed the plugin in sonatype-work/nexus3/plugin-repository, and restarted Nexus, however, I'm seeing no Packages.gz being created, no reference anywhere to this plugin, nor is there anything listed in any logs.  If it is compatible with 3.2.0, is there a way to verify if the plugin works?

**Comment by Tangresh** [comment]
As discussed in #24, this plugin is not compatible with Nexus 3 and will not be in the foreseeablbe future. Maybe you have better luck with this plugin: http://exchange.sonatype.com/details?extension=4719699238
