### ISSUE TITLE
Update the README to explicitly outline Nexus 3 non-compatibility

### ISSUE THREAD

**Issue by ju2wheels** [inventage/nexus-apt-plugin#32]
The current README doesnt say anywhere that its not compatible with Nexus 3, and the compatibility table only lists `2.11.x and greater` which one can naturally assume also includes 3.

I only noticed this one doesnt work on Nexus 3 after I built it and tried to figure out how to install it and stumbling upon some of the closed PRs.

It would have been a time saver to have known this and had it clearly spelled out in the README as well as potentially linking to the community Nexus 3 compatible repo as well.

**Comment by EugenMayer** [comment]
which one is compatible?

**Comment by ju2wheels** [comment]
https://github.com/sonatype-nexus-community/nexus-repository-apt
